// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9RLSP3yI11GwEIEEzhaPw44jnHusAqy4',
    appId: '1:184545609208:android:4bdf9f82bd0f827b98420d',
    messagingSenderId: '184545609208',
    projectId: 'uber-clone-5d2c9',
    databaseURL: 'https://uber-clone-5d2c9-default-rtdb.firebaseio.com',
    storageBucket: 'uber-clone-5d2c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_SXjc602W3DpLJF_D6kDLOAHM4DUK23Y',
    appId: '1:184545609208:ios:5a736f1179e39b5798420d',
    messagingSenderId: '184545609208',
    projectId: 'uber-clone-5d2c9',
    databaseURL: 'https://uber-clone-5d2c9-default-rtdb.firebaseio.com',
    storageBucket: 'uber-clone-5d2c9.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );
}
